import AlpineA110 from '../../assets/catalogue/alpine-a110.webp'
import AstonMartinAMRB001 from '../../assets/catalogue/aston-martin-amrb001.webp'
import AstonMartinDB11 from '../../assets/catalogue/aston-martin-db11.webp'
import AstonMartinDBSSuperleggera from '../../assets/catalogue/aston-martin-dbs-superleggera.webp'
import AstonMartinValhalla from '../../assets/catalogue/aston-martin-valhalla.webp'
import AstonMartinValkyrie from '../../assets/catalogue/aston-martin-valkyrie.webp'
import AstonMartinVantage from '../../assets/catalogue/aston-martin-vantage.webp'
import AudiA5 from '../../assets/catalogue/audi-a5.webp'
import AudiA5Cabrio from '../../assets/catalogue/audi-a5-cabrio.webp'
import AudiR8 from '../../assets/catalogue/audi-r8.webp'
import AudiR8Spyder from '../../assets/catalogue/audi-r8-spyder.webp'
import AudiTT from '../../assets/catalogue/audi-tt.webp'
import AudiTTRoadster from '../../assets/catalogue/audi-tt-rs-roadster.webp'
import AudiTTPerformance from '../../assets/catalogue/audi-tt-rs-performance.webp'
import AudiTTRS from '../../assets/catalogue/audi-tt-rs.webp'
import BugattiCentodieci from '../../assets/catalogue/bugatti-centodieci.webp'
import BugattiChironSuperSport from '../../assets/catalogue/bugatti-chiron-sport.webp'
import BugattiDivo from '../../assets/catalogue/bugatti-divo.webp'
import BugattiLaVoitureNoire from '../../assets/catalogue/bugatti-la-voiture-noire.webp'
import BugattiVeyronSuperSport from '../../assets/catalogue/bugatti-veyron-super-sport.webp'
import Chevrolet3100Apache1958 from '../../assets/catalogue/chevrolet-3100-apache-pickup-1958.webp'
import ChevroletCamaroSS from '../../assets/catalogue/chevrolet-camaro-ss.webp'
import ChevroletCamaroZL1 from '../../assets/catalogue/chevrolet-camaro-zl1.webp'
import ChevroletCamaroZL11LE from '../../assets/catalogue/chevrolet-camaro-zl1-1le.webp'
import ChevroletCorvetteC3Coupe1969 from '../../assets/catalogue/chevrolet-corvette-c3-coupe-1969.webp'
import ChevroletCorvetteC31969 from '../../assets/catalogue/chevrolet-corvette-c3-1969.webp'
import ChevroletCorvetteC8 from '../../assets/catalogue/chevrolet-corvette-c8-stingray.webp'
import ChevroletCorvetteZR1 from '../../assets/catalogue/chevrolet-corvette-zr1.webp'
import ChevroletCruzeHatchback from '../../assets/catalogue/chevrolet-cruze-hatchback.webp'
import ChevroletSilverado from '../../assets/catalogue/chevrolet-silverado.webp'

import Datsun240Z from '../../assets/catalogue/datsun-240z.webp'
import DeTomasoP722020 from '../../assets/catalogue/detomaso-p72-2020.webp'
import DodgeChallenger1970 from '../../assets/catalogue/dodge-challenger-1970.webp'
import DodgeChallengerSRTHellcat from '../../assets/catalogue/dodge-challenger-srt-hellcat-2019.webp'
import FordFiesta2017 from '../../assets/catalogue/ford-fiesta-2017.webp'
import FordFocusST2020 from '../../assets/catalogue/ford-focus-st-2020.webp'
import FordMustang1969 from '../../assets/catalogue/ford-mustang-1969.webp'
import FordMustangGT2018 from '../../assets/catalogue/ford-mustang-gt-2018.webp'
import HondaCivicTypeR2018 from '../../assets/catalogue/honda-civic-type-r-2018.webp'
import HondaVelosterN2019 from '../../assets/catalogue/hyundai-veloster-n-2019.webp'
import JaguarFType400Sport2018 from '../../assets/catalogue/jaguar-f-type-400-sport-2018.webp'
import JaguarFTypeSVR2018 from '../../assets/catalogue/jaguar-f-type-svr-2018.webp'
import JaguarFtypeSVRCabrio2018 from '../../assets/catalogue/jaguar-f-type-svr-cabrio-2018.webp'
import JaguarWranglerRubicon2018 from '../../assets/catalogue/jeep-wrangler-rubicon-2018.webp'
import KoenigseggJesko2020 from '../../assets/catalogue/koenigsegg-jesko-2020.webp'
import LotusRoverEvoque2020 from '../../assets/catalogue/land-rover-evoque-2020.webp'
import LotusRoverVelar2018 from '../../assets/catalogue/land-rover-velar-2018.webp'
import LotusEvija2019 from '../../assets/catalogue/lotus-evija-2019.webp'
import McLaren570sSpyder2018 from '../../assets/catalogue/mclaren-570s-spyder-2018.webp'
import McLaren600lt from '../../assets/catalogue/mclaren-600lt-2019.webp'
import McLaren720sSpider2019 from '../../assets/catalogue/mclaren-720s-spider-2019.webp'
import McLarenGT2020 from '../../assets/catalogue/mclaren-gt-2020.webp'
import McLarenSenna2019 from '../../assets/catalogue/mclaren-senna-2019.webp'
import McLarenSpeedatail2020 from '../../assets/catalogue/mclaren-speedtail-2020.webp'
import MercedesBenzA35AMG2019 from '../../assets/catalogue/mercedes-benz-a35-amg-2019.webp'
import MercedesBenzAMGGTRRoadster2020 from '../../assets/catalogue/mercedes-benz-amg-gt-roadster-2020.webp'
import MercedesBenzAMGGTR2020 from '../../assets/catalogue/mercedes-benz-amg-gtr-2020.webp'
import MercedesBenzC43AMG2019 from '../../assets/catalogue/mercedes-benz-c43-amg-2019.webp'
import MercedesBenzC63AMGS2019 from '../../assets/catalogue/mercedes-benz-c63-amg-s-2019.webp'
import MercedesBenzClassCAMG2019 from '../../assets/catalogue/mercedes-benz-class-c-amg-2019.webp'
import MercedesBenzE53AMG2019 from '../../assets/catalogue/mercedes-benz-e53-amg-2019.webp'
import MercedesBenzGLBAMG2020 from '../../assets/catalogue/mercedes-benz-glb-amg-2020.webp'
import MercedesBenzS63AMG2018 from '../../assets/catalogue/mercedes-benz-s63-amg-2018.webp'
import MercedesBenzSSRoadster1930 from '../../assets/catalogue/mercedes-benz-ss-roadster-1930.webp'
import MorganAeroGT2018 from '../../assets/catalogue/morgan-aero-gt-2018.webp'
import NissanGTR2018 from '../../assets/catalogue/nissan-gt-r-2018.webp'
import NissanTitan2020 from '../../assets/catalogue/nissan-titan-2020.webp'
import PaganiHuaydraBC from '../../assets/catalogue/pagani-huaydra-bc-2017.webp'
import PaganiHuaydraRoadster2017 from '../../assets/catalogue/pagani-huaydra-roadster-2017.webp'
import PaganiHuaydraRoadster2020 from '../../assets/catalogue/pagani-huaydra-roadster-2020.webp'
import Porsche3561955 from '../../assets/catalogue/porsche-356-1955.webp'
import Porsche3561948 from '../../assets/catalogue/porsche-356-1948.webp'
import Porsche718BoxsterSpyder from '../../assets/catalogue/porsche-718-boxster-spyder-2020.webp'
import Porsche911Carrera964 from '../../assets/catalogue/porsche-911-964-carrera-1990.webp'
import Porsche911Turbo964 from '../../assets/catalogue/porsche-911-964-turbo-1990.webp'
import Porsche911Carrera4sCabrio2019 from '../../assets/catalogue/porsche-911-carrera-4s-cabrio-2019.webp'
import Porsche911CarreraRS1973 from '../../assets/catalogue/porsche-911-carrera-rs-1973.webp'
import Porsche911GT2RS2018 from '../../assets/catalogue/porsche-911-gt2-rs-2018.webp'
import Porsche911GT32018 from '../../assets/catalogue/porsche-911-gt3-2018.webp'
import Porsche911GT3RS from '../../assets/catalogue/porsche-911-gt3-rs-2019.webp'
import Porsche911TurboS2018 from '../../assets/catalogue/porsche-911-turbo-s-2018.webp'
import Porsche924 from '../../assets/catalogue/porsche-924.webp'
import PorscheCayanne2020 from '../../assets/catalogue/porsche-cayanne-2020.webp'
import PorscheCayman718GTS2018 from '../../assets/catalogue/porsche-cayman-718-GTS-2018.webp'
import PorscheMecan2019 from '../../assets/catalogue/porsche-mecan-2019.webp'
import PorschePanameraGTS2019 from '../../assets/catalogue/porsche-panamera-gts-2019.webp'
import PorschePanameraGTSSportTurismo2019 from '../../assets/catalogue/porsche-panamera-gts-sport-turismo-2019.webp'
import Porsche911GT3Touring2018 from '../../assets/catalogue/porsche-911-gt3-touring-2018.webp'
import PorscheSpeedster2019 from '../../assets/catalogue/porsche-911-speedster-2019.webp'
import PorscheSpyder5501953 from '../../assets/catalogue/porsche-spyder-550-1953.webp'
import PorscheTaycan2020 from '../../assets/catalogue/porsche-taycan-2020.webp'
import PorscheTaycanS2020 from '../../assets/catalogue/porsche-taycan-s-2020.webp'
import RangeRoverSportSVR2018 from '../../assets/catalogue/range-rover-sport-svr-2018.webp'
import RangeRoverSV2019 from '../../assets/catalogue/range-rover-sv-2019.webp'
import SubaruBRZ2018 from '../../assets/catalogue/subaru-brz-2018.webp'
import SubaruImpresaWRX2018 from '../../assets/catalogue/subaru-impresa-wrx-2018.webp'
import SubaruWRXSTI2018 from '../../assets/catalogue/subaru-wrx-sti-2018.webp'
import TeslaModelY from '../../assets/catalogue/tesla-model-y-2021.webp'
import TeslaRoadster from '../../assets/catalogue/tesla-roadster-2020.webp'
import ToyotaAvalonTRD2020 from '../../assets/catalogue/toyota-avalon-trd-2020.webp'
import ToyotaCamryTRD2020 from '../../assets/catalogue/toyota-camry-trd-2020.webp'
import ToyotaSupra2020 from '../../assets/catalogue/toyota-supra-2020.webp'
import VolkswagenGolfSportvan2018 from '../../assets/catalogue/volkswagen-golf-sportsvan-2018.webp'
import VolkswagenPoloGT2018 from '../../assets/catalogue/volkswagen-polo-gt-2018.webp'

const CarsData = [
  {
    id: 1,
    title: 'Alpine A110',
    bodywork: 'Coupé',
    image: AlpineA110,
    topSpeed: '250',
    acceleration: '4.5',
    passengers: '2',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 2,
    title: 'AstonMartin AM-RB 001',
    bodywork: 'Coupé',
    image: AstonMartinAMRB001,
    topSpeed: '400',
    acceleration: '3.2',
    passengers: '2',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 3,
    title: 'Aston Martin DB11',
    bodywork: 'Coupé',
    image: AstonMartinDB11,
    topSpeed: '322',
    acceleration: '3.9',
    passengers: '4',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 4,
    title: 'Aston Martin DBS Superleggera',
    bodywork: 'Coupé',
    image: AstonMartinDBSSuperleggera,
    topSpeed: '339',
    acceleration: '3.6',
    passengers: '4',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 5,
    title: 'Aston Martin Valhalla',
    bodywork: 'Coupé',
    image: AstonMartinValhalla,
    topSpeed: '350',
    acceleration: '2.5',
    passengers: '2',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 6,
    title: 'Aston Martin Vantage',
    bodywork: 'Coupé',
    image: AstonMartinVantage,
    topSpeed: '325',
    acceleration: '3.6',
    passengers: '2',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 7,
    title: 'Aston Martin Valkyrie',
    bodywork: 'Coupé',
    image: AstonMartinValkyrie,
    topSpeed: '330',
    acceleration: '2.5',
    passengers: '2',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 8,
    title: 'Audi A5',
    bodywork: 'Coupé',
    image: AudiA5,
    topSpeed: '250',
    acceleration: '4.6',
    passengers: '4',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 9,
    title: 'Audi A5 Cabrio',
    bodywork: 'Coupé',
    image: AudiA5Cabrio,
    topSpeed: '250',
    acceleration: '4.6',
    passengers: '4',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 11,
    title: 'Audi R8',
    bodywork: 'Coupé',
    image: AudiR8,
    topSpeed: '331',
    acceleration: '3.1',
    passengers: '2',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 12,
    title: 'Audi R8 Spyder',
    bodywork: 'Coupé',
    image: AudiR8Spyder,
    topSpeed: '331',
    acceleration: '3.1',
    passengers: '2',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 13,
    title: 'Audi TT',
    bodywork: 'Coupé',
    image: AudiTT,
    topSpeed: '250',
    acceleration: '5.3',
    passengers: '4',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 14,
    title: 'Audi TT Roadster',
    bodywork: 'Coupé',
    image: AudiTTRoadster,
    topSpeed: '250',
    acceleration: '5.3',
    passengers: '2',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 15,
    title: 'Audi TT Performance',
    bodywork: 'Coupé',
    image: AudiTTPerformance,
    topSpeed: '280',
    acceleration: '4.6',
    passengers: '4',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 16,
    title: 'Audi TT RS',
    bodywork: 'Coupé',
    image: AudiTTRS,
    topSpeed: '250',
    acceleration: '3.7',
    passengers: '4',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 17,
    title: 'Bugatti Centodieci',
    bodywork: 'Coupé',
    image: BugattiCentodieci,
    topSpeed: '380',
    acceleration: '2.4',
    passengers: '2',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 18,
    title: 'Bugatti Chiron Super Sport',
    bodywork: 'Coupé',
    image: BugattiChironSuperSport,
    topSpeed: '440',
    acceleration: '2.5',
    passengers: '2',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 19,
    title: 'Bugatti Divo',
    bodywork: 'Coupé',
    image: BugattiDivo,
    topSpeed: '380',
    acceleration: '2.4',
    passengers: '2',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 20,
    title: 'Bugatti La Voiture Noire',
    bodywork: 'Coupé',
    image: BugattiLaVoitureNoire,
    topSpeed: '420',
    acceleration: '2.5',
    passengers: '2',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 21,
    title: 'Bugatti Veyron Super Sport',
    bodywork: 'Coupé',
    image: BugattiVeyronSuperSport,
    topSpeed: '415',
    acceleration: '2.5',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 22,
    title: 'Chevrolet 3100 Apache',
    bodywork: 'Pickup',
    image: Chevrolet3100Apache1958,
    topSpeed: '140',
    acceleration: '',
    passengers: '3',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 23,
    title: 'Chevrolet Camaro SS',
    bodywork: 'Coupé',
    image: ChevroletCamaroSS,
    topSpeed: '250',
    acceleration: '4.2',
    passengers: '4',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 24,
    title: 'Chevrolet Camaro ZL1',
    bodywork: 'Coupé',
    image: ChevroletCamaroZL1,
    topSpeed: '325',
    acceleration: '3.5',
    passengers: '4',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 25,
    title: 'Chevrolet Camaro ZL1 1LE',
    bodywork: 'Coupé',
    image: ChevroletCamaroZL11LE,
    topSpeed: '325',
    acceleration: '3.5',
    passengers: '4',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 26,
    title: 'Chevrolet Corvette C3',
    bodywork: 'Coupé',
    image: ChevroletCorvetteC3Coupe1969,
    topSpeed: '245',
    acceleration: '',
    passengers: '2',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 27,
    title: 'Chevrolet Corvette C3',
    bodywork: 'Roadster',
    image: ChevroletCorvetteC31969,
    topSpeed: '245',
    acceleration: '',
    passengers: '2',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 28,
    title: 'Chevrolet Corvette C8',
    bodywork: 'Coupé',
    image: ChevroletCorvetteC8,
    topSpeed: '312',
    acceleration: '3.0',
    passengers: '2',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 29,
    title: 'Chevrolet Corvette ZR1',
    bodywork: 'Coupé',
    image: ChevroletCorvetteZR1,
    topSpeed: '341',
    acceleration: '2.9',
    passengers: '2',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 30,
    title: 'Chevrolet Corvette Cruze Hatchback',
    bodywork: 'Sedán',
    image: ChevroletCruzeHatchback,
    topSpeed: '209',
    acceleration: '9',
    passengers: '5',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 31,
    title: 'Chevrolet Silverado',
    bodywork: 'Pickup',
    image: ChevroletSilverado,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 8,
    title: 'Datsun 240Z',
    bodywork: '',
    image: Datsun240Z,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 8,
    title: 'DeTomaso P72 2020',
    bodywork: '',
    image: DeTomasoP722020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 7,
    title: 'Dodge Challenger 1970',
    bodywork: '',
    image: DodgeChallenger1970,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 7,
    title: 'Dodge Challenger SRT Hellcat',
    bodywork: 'Coupé',
    image: DodgeChallengerSRTHellcat,
    topSpeed: '314',
    acceleration: '3.6',
    passengers: '5',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 8,
    title: 'Ford Fiesta',
    bodywork: '',
    image: FordFiesta2017,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 8,
    title: 'Ford Focus ST',
    bodywork: '',
    image: FordFocusST2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 8,
    title: 'Ford Mustang 1969',
    bodywork: '',
    image: FordMustang1969,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 8,
    title: 'Ford Mustang GT',
    bodywork: '',
    image: FordMustangGT2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 8,
    title: 'Honda Civic Type-R',
    bodywork: '',
    image: HondaCivicTypeR2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 8,
    title: 'Honda Veloster N',
    bodywork: '',
    image: HondaVelosterN2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 8,
    title: 'Jaguar FType 400 Sport',
    bodywork: '',
    image: JaguarFType400Sport2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 8,
    title: 'Jaguar F-Type SVR',
    bodywork: '',
    image: JaguarFTypeSVR2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 8,
    title: 'Jaguar F-Type SVR Cabrio',
    bodywork: '',
    image: JaguarFtypeSVRCabrio2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 8,
    title: 'Jaguar Wrangler Rubicon',
    bodywork: '',
    image: JaguarWranglerRubicon2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 8,
    title: 'Koenigsegg Jesko',
    bodywork: '',
    image: KoenigseggJesko2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 9,
    title: 'Lotus Rover Evoque',
    bodywork: '',
    image: LotusRoverEvoque2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 9,
    title: 'Lotus Rover Velar',
    bodywork: '',
    image: LotusRoverVelar2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 9,
    title: 'Lotus Evija',
    bodywork: '',
    image: LotusEvija2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 10,
    title: 'McLaren 570s Spyder',
    bodywork: '',
    image:  McLaren570sSpyder2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 10,
    title: 'McLaren 600lt',
    bodywork: '',
    image:  McLaren600lt,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 10,
    title: 'McLaren 720S Spider',
    bodywork: '',
    image:  McLaren720sSpider2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 11,
    title: 'McLaren GT',
    bodywork: '',
    image: McLarenGT2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 11,
    title: 'McLaren Senna',
    bodywork: '',
    image: McLarenSenna2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 11,
    title: 'McLaren Speedatail',
    bodywork: '',
    image: McLarenSpeedatail2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 12,
    title: 'Mercedes Benz A35 AMG',
    bodywork: '',
    image:  MercedesBenzA35AMG2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 12,
    title: 'Mercedes Benz AMG GTR',
    bodywork: 'Roadster',
    image:  MercedesBenzAMGGTRRoadster2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 12,
    title: 'Mercedes Benz AMG GTR',
    bodywork: '',
    image:  MercedesBenzAMGGTR2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 14,
    title: 'Mercedes C43 AMG',
    bodywork: '',
    image: MercedesBenzC43AMG2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 14,
    title: 'Mercedes C63 AMG S',
    bodywork: '',
    image: MercedesBenzC63AMGS2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 14,
    title: 'Mercedes Class C AMG',
    bodywork: '',
    image: MercedesBenzClassCAMG2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 14,
    title: 'Mercedes E53 AMG',
    bodywork: '',
    image: MercedesBenzE53AMG2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 13,
    title: 'Mercedes Benz GLB AMG',
    bodywork: '',
    image:  MercedesBenzGLBAMG2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 12,
    title: 'Mercedes Benz S63 AMG',
    bodywork: '',
    image:  MercedesBenzS63AMG2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 12,
    title: 'Mercedes SS Roadster 1930',
    bodywork: '',
    image:  MercedesBenzSSRoadster1930,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 12,
    title: 'Morgan Aero GT',
    bodywork: '',
    image:  MorganAeroGT2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 15,
    title: 'Nissan GTR',
    bodywork: '',
    image:  NissanGTR2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 15,
    title: 'Nissan Titan',
    bodywork: '',
    image:  NissanTitan2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 15,
    title: 'PaganiHuaydraBC',
    bodywork: '',
    image:  PaganiHuaydraBC,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 15,
    title: 'Pagani Huaydra Roadster',
    bodywork: '',
    image:  PaganiHuaydraRoadster2017,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 15,
    title: 'Pagani Huaydra Roadster',
    bodywork: '',
    image:  PaganiHuaydraRoadster2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 16,
    title: 'Porsche 356 1948',
    bodywork: '',
    image: Porsche3561948,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 16,
    title: 'Porsche 356 1955',
    bodywork: '',
    image: Porsche3561955,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 16,
    title: 'Porsche 718 Boxster Spyder',
    bodywork: '',
    image: Porsche718BoxsterSpyder,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 16,
    title: 'Porsche 911 Carrera 964',
    bodywork: '',
    image: Porsche911Carrera964,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 16,
    title: 'Porsche 911 Turbo 964',
    bodywork: '',
    image: Porsche911Turbo964,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 16,
    title: 'Porsche 911 Carrera 4s Cabrio',
    bodywork: '',
    image: Porsche911Carrera4sCabrio2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 16,
    title: 'Porsche 911 Carrera RS 1973',
    bodywork: '',
    image: Porsche911CarreraRS1973,
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 16,
    title: 'Porsche 911 GT2 RS',
    bodywork: '',
    image: Porsche911GT2RS2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 16,
    title: 'Porsche 911 GT3',
    bodywork: '',
    image: Porsche911GT32018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 16,
    title: 'Porsche 911 GT3 RS',
    bodywork: 'Coupé',
    image: Porsche911GT3RS,
    topSpeed: '312',
    acceleration: '3.2',
    passengers: '2',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 17,
    title: 'Porsche 911 Turbo S',
    bodywork: '',
    image:  Porsche911TurboS2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 17,
    title: 'Porsche 924',
    bodywork: '',
    image:  Porsche924,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 19,
    title: 'Porsche Cayanne',
    bodywork: '',
    image:  PorscheCayanne2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 20,
    title: 'Porsche Cayman 718 GTS',
    bodywork: '',
    image:  PorscheCayman718GTS2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 17,
    title: 'Porsche Mecan',
    bodywork: '',
    image:  PorscheMecan2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 20,
    title: 'Porsche Panamera GTS',
    bodywork: '',
    image:  PorschePanameraGTS2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 20,
    title: 'Porsche Panamera GTS Sport Turismo',
    bodywork: '',
    image:  PorschePanameraGTSSportTurismo2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 17,
    title: 'Porsche 911 GT3 Touring',
    bodywork: '',
    image:  Porsche911GT3Touring2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 20,
    title: 'Porsche Speedster',
    bodywork: '',
    image:  PorscheSpeedster2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 20,
    title: 'Porsche 550 Spyder',
    bodywork: '',
    image:  PorscheSpyder5501953,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 21,
    title: 'Porsche Taycan',
    bodywork: 'Berlina',
    image: PorscheTaycan2020,
    topSpeed: '260',
    acceleration: '3.4',
    passengers: '4',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 21,
    title: 'Porsche Taycan S',
    bodywork: 'Berlina',
    image: PorscheTaycanS2020,
    topSpeed: '260',
    acceleration: '3.4',
    passengers: '4',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 23,
    title: 'Range Rover Sport SVR',
    bodywork: '',
    image: RangeRoverSportSVR2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 23,
    title: 'Range Rover SV',
    bodywork: '',
    image: RangeRoverSV2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 23,
    title: 'Subaru BRZ',
    bodywork: '',
    image: SubaruBRZ2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 23,
    title: 'Subaru Impresa WRX',
    bodywork: '',
    image: SubaruImpresaWRX2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 23,
    title: 'Subaru WRX STI',
    bodywork: '',
    image: SubaruWRXSTI2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 22,
    title: 'Tesla Model Y',
    bodywork: 'Sedán',
    image: TeslaModelY,
    topSpeed: '225',
    acceleration: '5.6',
    passengers: '5',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 23,
    title: 'Tesla Roadster',
    bodywork: '',
    image: TeslaRoadster,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 24,
    title: 'Toyota Avalon TRD',
    bodywork: '',
    image: ToyotaAvalonTRD2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 24,
    title: 'Toyota Camry TRD',
    bodywork: '',
    image: ToyotaCamryTRD2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 24,
    title: 'Toyota Supra',
    bodywork: '',
    image: ToyotaSupra2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 24,
    title: 'Volkswagen Golf Sportvan',
    bodywork: '',
    image: VolkswagenGolfSportvan2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 24,
    title: 'Volkswagen Polo GT',
    bodywork: '',
    image: VolkswagenPoloGT2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
]

export default CarsData