import AlpineA110 from '../../assets/catalogue/alpine a110-2018.webp'
import AstonMartinAMRB001 from '../../assets/catalogue/aston-martin-am-rb-001-2018.webp'
import AstonMartinDB112018 from '../../assets/catalogue/aston-martin-db11-2018.webp'
import AstonMartinDB112019 from '../../assets/catalogue/aston-martin-db11-2019.webp'
import AstonMartinDBSSuperleggera2019 from '../../assets/catalogue/aston-martin-dbs-superleggera-2019.webp'
import AstonMartinValhalla2020 from '../../assets/catalogue/aston-martin-valhalla-2020.webp'
import AstonMartinValkyrie2018 from '../../assets/catalogue/aston-martin-valkyrie-2018.webp'
import AstonMartinVantage2019 from '../../assets/catalogue/aston-martin-vantage-2019.webp'
import AudiA52020 from '../../assets/catalogue/audi-a5-2020.webp'
import AudiA5Cabrio2020 from '../../assets/catalogue/audi-a5-cabrio-2020.webp'
import AudiA5Sportback2020 from '../../assets/catalogue/audi-a5-sportback-2020.webp'
import AudiR82019 from '../../assets/catalogue/audi-r8-2019.webp'
import AudiR8Spyder2019 from '../../assets/catalogue/audi-r8-spyder-2019.webp'
import AudiR8LMSGT32020 from '../../assets/catalogue/audi-r8-lms-gt3-2020.webp'
import AudiTT2019 from '../../assets/catalogue/audi-tt-2019.webp'
import AudiTTRS2020 from '../../assets/catalogue/audi-ttrs-2020.webp'
import AudiTTPerformance2018 from '../../assets/catalogue/audi-ttrs-performance-2018.webp'
import AudiTTRoadster2020 from '../../assets/catalogue/audi-ttrs-roadster-2020.webp'
import AudiTTS2018 from '../../assets/catalogue/audi-tts-2018.webp'
import BentleyContinentalGT3 from '../../assets/catalogue/bentley-continental-gt3-2018.webp'
import BugattiCentodieci from '../../assets/catalogue/bugatti-centodieci-2020.webp'
import BugattiChironSport2019 from '../../assets/catalogue/bugatti-chiron-sport-2019.webp'
import BugattiDivo from '../../assets/catalogue/bugatti-divo-2019.webp'
import BugattiLaVoitureNoire from '../../assets/catalogue/bugatti-la-voiture-noire-2019.webp'
import BugattiVeyronSuperSport from '../../assets/catalogue/bugatti-veyron-super-sport.webp'
import Chevrolet3100Apache1958 from '../../assets/catalogue/chevrolet-3100-apache-pickup-1958.webp'
import ChevroletCamaroSS1LE2019 from '../../assets/catalogue/chevrolet-camaro-ss-1le-2019.webp'
import ChevroletCamaroSS2019 from '../../assets/catalogue/chevrolet-camaro-ss-2019.webp'
import ChevroletCamaroZL11LE from '../../assets/catalogue/chevrolet-camaro-zl1-1le-2019.webp'
import ChevroletCamaroZL1 from '../../assets/catalogue/chevrolet-camaro-zl1.webp'
import ChevroletCorvetteC31969 from '../../assets/catalogue/chevrolet-corvette-c3-1969.webp'
import ChevroletCorvetteC32020 from '../../assets/catalogue/chevrolet-corvette-c3-convertible-1969.webp'
import ChevroletCorvetteC82020 from '../../assets/catalogue/chevrolet-corvette-c8-2020-stingray.webp'
import ChevroletCorvetteZR12019 from '../../assets/catalogue/chevrolet-corvette-zr1-2019.webp'
import ChevroletCruzeHatchback2019 from '../../assets/catalogue/chevrolet-cruze-hatchback-2019.webp'
import ChevroletSilverado2020 from '../../assets/catalogue/chevrolet-silverado-2020.webp'
import Datsun240Z from '../../assets/catalogue/datsun-240z.webp'
import DeTomasoP722020 from '../../assets/catalogue/detomaso-p72-2020.webp'
import DodgeChallenger1970 from '../../assets/catalogue/dodge-challenger-1970.webp'
import DodgeChallengerSRTDemon2018 from '../../assets/catalogue/dodge-challenger-srt-demon-2018.webp'
import DodgeChallengerSRTHellcat2019 from '../../assets/catalogue/dodge-challenger-srt-hellcat-2019.webp'
import DodgeChallengerSRTHellcatWidebody from '../../assets/catalogue/dodge-challenger-srt-hellcat-widebody-2018.webp'
import DodgeChargerSRTHellcat2019 from '../../assets/catalogue/dodge-charger-srt-hellcat-2019.webp'
import FordFiesta2017 from '../../assets/catalogue/ford-fiesta-2017.webp'
import FordFocusST2020 from '../../assets/catalogue/ford-focus-st-2020.webp'
import FordMustang1969 from '../../assets/catalogue/ford-mustang-1969.webp'
import FordMustangGT2018 from '../../assets/catalogue/ford-mustang-gt-2018.webp'
import JaguarFTypeSVR2018 from '../../assets/catalogue/jaguar-f-type-svr-2018.webp'
import JaguarFtypeSVRCabrio2018 from '../../assets/catalogue/jaguar-f-type-svr-cabrio-2018.webp'
import KoenigseggJesko2020 from '../../assets/catalogue/koenigsegg-jesko-2020.webp'
import LotusEvija2019 from '../../assets/catalogue/lotus-evija-2019.webp'
import McLaren570sSpyder2018 from '../../assets/catalogue/mclaren-570s-spyder-2018.webp'
import McLaren600lt from '../../assets/catalogue/mclaren-600lt-2019.webp'
import McLaren720sSpider2019 from '../../assets/catalogue/mclaren-720s-spider-2019.webp'
import McLarenGT2020 from '../../assets/catalogue/mclaren-gt-2020.webp'
import McLarenSenna2019 from '../../assets/catalogue/mclaren-senna-2019.webp'
import McLarenSpeedatail2020 from '../../assets/catalogue/mclaren-speedtail-2020.webp'
import McLarenUltimateVisionGranTurismo from '../../assets/catalogue/mclaren-ultimate-vision-gran-turismo.webp'
import MercedesBenzAMGGTR2020 from '../../assets/catalogue/mercedes-benz-amg-gtr-2020.webp'
import MercedesBenzGLBAMG2020 from '../../assets/catalogue/mercedes-benz-glb-amg-2020.webp'
import MercedesBenzS63AMG2018 from '../../assets/catalogue/mercedes-benz-s63-amg-2018.webp'
import MercedesBenzC43AMG2019 from '../../assets/catalogue/mercedes-benz-c43-amg-2019.webp'
import MorganAeroGT2018 from '../../assets/catalogue/morgan-aero-gt-2018.webp'
import NissanGTR2018 from '../../assets/catalogue/nissan-gt-r-2018.webp'
import NissanTitan2020 from '../../assets/catalogue/nissan-titan-2020.webp'
import PaganiHuaydraBC from '../../assets/catalogue/pagani-huaydra-bc-2017.webp'
import PaganiHuaydraRoadster2017 from '../../assets/catalogue/pagani-huaydra-roadster-2017.webp'
import PaganiHuaydraRoadster2020 from '../../assets/catalogue/pagani-huaydra-roadster-2020.webp'
import Porsche718BoxsterSpyder from '../../assets/catalogue/porsche-718-boxster-spyder-2020.webp'
import Porsche911Carrera4sCabrio2019 from '../../assets/catalogue/porsche-911-carrera-4s-cabrio-2019.webp'
import Porsche911GT2RS2018 from '../../assets/catalogue/porsche-911-gt2-rs-2018.webp'
import Porsche911GT32018 from '../../assets/catalogue/porsche-911-gt3-2018.webp'
import Porsche911GT3RS from '../../assets/catalogue/porsche-911-gt3-rs-2019.webp'
import Porsche911Turbo1990 from '../../assets/catalogue/porsche-911-turbo-1990.webp'
import Porsche9352019 from '../../assets/catalogue/porsche-935-2019.webp'
import PorscheCayanne2020 from '../../assets/catalogue/porsche-cayanne-2020.webp'
import PorscheCayanneTurbo2020 from '../../assets/catalogue/porsche-cayanne-turbo-2020.webp'
import PorscheCayman718GTS2018 from '../../assets/catalogue/porsche-cayman-718-GTS-2018.webp'
import PorschePanameraGTS2019 from '../../assets/catalogue/porsche-panamera-gts-2019.webp'
import PorschePanameraGTSSportTurismo2019 from '../../assets/catalogue/porsche-panamera-gts-sport-turismo-2019.webp'
import PorscheSpeedster2019 from '../../assets/catalogue/porsche-911-speedster-2019.webp'
import PorscheSpyder5501953 from '../../assets/catalogue/porsche-spyder-550-1953.webp'
import PorscheTaycan2020 from '../../assets/catalogue/porsche-taycan-2020.webp'
import PorscheTaycanS2020 from '../../assets/catalogue/porsche-taycan-s-2020.webp'
import RangeRoverSportSVR2018 from '../../assets/catalogue/range-rover-sport-svr-2018.webp'
import SquirV2 from '../../assets/catalogue/squir-v2-2018.webp'
import SubaruBRZ2018 from '../../assets/catalogue/subaru-brz-2018.webp'
import SubaruImpresaWRX2018 from '../../assets/catalogue/subaru-impresa-wrx-2018.webp'
import SubaruWRXSTI2018 from '../../assets/catalogue/subaru-wrx-sti-2018.webp'
import TeslaModelY from '../../assets/catalogue/tesla-model-y-2021.webp'
import TeslaRoadster from '../../assets/catalogue/tesla-roadster-2020.webp'
import ToyotaSupra2020 from '../../assets/catalogue/toyota-supra-2020.webp'

const CarsData = [
  {
    id: 1,
    title: 'Alpine A110',
    bodywork: '',
    image: AlpineA110,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 1,
    title: 'AstonMartin AM-RB 001',
    bodywork: '',
    image: AstonMartinAMRB001,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 1,
    title: 'Aston Martin DB11 2018',
    bodywork: '',
    image: AstonMartinDB112018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 1,
    title: 'Aston Martin DB11 2019',
    bodywork: '',
    image: AstonMartinDB112019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 1,
    title: 'Aston Martin DBS Superleggera',
    bodywork: '',
    image: AstonMartinDBSSuperleggera2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 1,
    title: 'Aston Martin Valhalla',
    bodywork: '',
    image: AstonMartinValhalla2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 1,
    title: 'Aston Martin Vantage',
    bodywork: '',
    image: AstonMartinVantage2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 1,
    title: 'Aston Martin Valkyrie',
    bodywork: '',
    image: AstonMartinValkyrie2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 1,
    title: 'Audi A5',
    bodywork: '',
    image: AudiA52020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 1,
    title: 'Audi A5 Cabrio',
    bodywork: '',
    image: AudiA5Cabrio2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 1,
    title: 'Audi A5 Sportback',
    bodywork: '',
    image: AudiA5Sportback2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 2,
    title: 'Audi R8',
    bodywork: 'Coupé',
    image: AudiR82019,
    topSpeed: '331',
    acceleration: '3.1',
    passengers: '2',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 3,
    title: 'Audi R8 Spyder',
    bodywork: '',
    image: AudiR8Spyder2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 3,
    title: 'Audi R8 LMS GT3',
    bodywork: '',
    image: AudiR8LMSGT32020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 3,
    title: 'Audi TT',
    bodywork: '',
    image: AudiTT2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 3,
    title: 'Audi TT Performance',
    bodywork: '',
    image: AudiTTPerformance2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 3,
    title: 'Audi TT RS',
    bodywork: '',
    image: AudiTTRS2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 3,
    title: 'Audi TT Roadster',
    bodywork: '',
    image: AudiTTRoadster2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 3,
    title: 'Audi TTS',
    bodywork: '',
    image: AudiTTS2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 4,
    title: 'Bentley Continental GT3',
    bodywork: '',
    image: BentleyContinentalGT3,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 4,
    title: 'Bugatti Centodieci',
    bodywork: '',
    image: BugattiCentodieci,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 4,
    title: 'Bugatti Chiron Sport',
    bodywork: 'Coupé',
    image: BugattiChironSport2019,
    topSpeed: '420',
    acceleration: '2.4',
    passengers: '2',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 4,
    title: 'Bugatti Divo',
    bodywork: '',
    image: BugattiDivo,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 4,
    title: 'Bugatti La Voiture Noire',
    bodywork: '',
    image: BugattiLaVoitureNoire,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 4,
    title: 'Bugatti Veyron Super Sport',
    bodywork: '',
    image: BugattiVeyronSuperSport,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 5,
    title: 'Chevrolet 3100 Apache',
    bodywork: '',
    image: Chevrolet3100Apache1958,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 5,
    title: 'Chevrolet Camaro SS 1LE',
    bodywork: '',
    image: ChevroletCamaroSS1LE2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 5,
    title: 'Chevrolet Camaro SS',
    bodywork: 'Coupé',
    image: ChevroletCamaroSS2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 5,
    title: 'Chevrolet Camaro ZL1 1LE',
    bodywork: 'Coupé',
    image: ChevroletCamaroZL11LE,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 5,
    title: 'Chevrolet Camaro ZL1',
    bodywork: 'Coupé',
    image: ChevroletCamaroZL1,
    topSpeed: '325',
    acceleration: '3.5',
    passengers: '4',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 5,
    title: 'Chevrolet Corvette C3 1969',
    bodywork: '',
    image: ChevroletCorvetteC31969,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 5,
    title: 'Chevrolet Corvette C3 2020',
    bodywork: '',
    image: ChevroletCorvetteC32020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 5,
    title: 'Chevrolet Corvette C8',
    bodywork: '',
    image: ChevroletCorvetteC82020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 5,
    title: 'Chevrolet Corvette ZR1',
    bodywork: '',
    image: ChevroletCorvetteZR12019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 5,
    title: 'Chevrolet Corvette Cruze Hatchback',
    bodywork: '',
    image: ChevroletCruzeHatchback2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 6,
    title: 'Chevrolet Silverado 2020',
    bodywork: '',
    image: ChevroletSilverado2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 8,
    title: 'Datsun 240Z',
    bodywork: '',
    image: Datsun240Z,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 8,
    title: 'DeTomaso P72 2020',
    bodywork: '',
    image: DeTomasoP722020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 7,
    title: 'Dodge Challenger 1970',
    bodywork: 'Coupé',
    image: DodgeChallenger1970,
    topSpeed: '314',
    acceleration: '3.6',
    passengers: '5',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 7,
    title: 'Dodge Challenger SRT Demon',
    bodywork: 'Coupé',
    image: DodgeChallengerSRTDemon2018,
    topSpeed: '314',
    acceleration: '3.6',
    passengers: '5',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 7,
    title: 'Dodge Challenger SRT Hellcat',
    bodywork: 'Coupé',
    image: DodgeChallengerSRTHellcat2019,
    topSpeed: '314',
    acceleration: '3.6',
    passengers: '5',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 8,
    title: 'Dodge Challenger SRT Hellcat Widebody',
    bodywork: '',
    image: DodgeChallengerSRTHellcatWidebody,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 8,
    title: 'Dodge Charger SRT Hellcat',
    bodywork: '',
    image: DodgeChargerSRTHellcat2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 8,
    title: 'Ford Fiesta',
    bodywork: '',
    image: FordFiesta2017,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 8,
    title: 'Ford Focus ST',
    bodywork: '',
    image: FordFocusST2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 8,
    title: 'Ford Mustang 1969',
    bodywork: '',
    image: FordMustang1969,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 8,
    title: 'Ford Mustang GT',
    bodywork: '',
    image: FordMustangGT2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 8,
    title: 'Jaguar F-Type SVR',
    bodywork: '',
    image: JaguarFTypeSVR2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 8,
    title: 'Jaguar F-Type SVR Cabrio',
    bodywork: '',
    image: JaguarFtypeSVRCabrio2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 8,
    title: 'Koenigsegg Jesko',
    bodywork: '',
    image: KoenigseggJesko2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 9,
    title: 'Lotus Evija',
    bodywork: '',
    image: LotusEvija2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 10,
    title: 'McLaren 570s Spyder',
    bodywork: '',
    image:  McLaren570sSpyder2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 10,
    title: 'McLaren 600lt',
    bodywork: '',
    image:  McLaren600lt,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 10,
    title: 'McLaren 720S Spider',
    bodywork: '',
    image:  McLaren720sSpider2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 11,
    title: 'McLaren GT',
    bodywork: '',
    image: McLarenGT2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 11,
    title: 'McLaren Senna',
    bodywork: '',
    image: McLarenSenna2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 11,
    title: 'McLaren Speedatail',
    bodywork: '',
    image: McLarenSpeedatail2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 11,
    title: 'McLaren Ultimate Vision Gran Turismo',
    bodywork: '',
    image: McLarenUltimateVisionGranTurismo,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 12,
    title: 'Mercedes Benz AMG GTR',
    bodywork: '',
    image:  MercedesBenzAMGGTR2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 13,
    title: 'Mercedes Benz GLB AMG',
    bodywork: '',
    image:  MercedesBenzGLBAMG2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 14,
    title: 'Mercedes C43 AMG',
    bodywork: '',
    image: MercedesBenzC43AMG2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 12,
    title: 'Mercedes Benz S63 AMG',
    bodywork: '',
    image:  MercedesBenzS63AMG2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 12,
    title: 'Morgan Aero GT',
    bodywork: '',
    image:  MorganAeroGT2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 15,
    title: 'Nissan GTR',
    bodywork: '',
    image:  NissanGTR2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 15,
    title: 'Nissan Titan',
    bodywork: '',
    image:  NissanTitan2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 15,
    title: 'PaganiHuaydraBC',
    bodywork: '',
    image:  PaganiHuaydraBC,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 15,
    title: 'Pagani Huaydra Roadster',
    bodywork: '',
    image:  PaganiHuaydraRoadster2017,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 15,
    title: 'Pagani Huaydra Roadster',
    bodywork: '',
    image:  PaganiHuaydraRoadster2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 16,
    title: 'Porsche 718 Boxster Spyder',
    bodywork: '',
    image: Porsche718BoxsterSpyder,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 16,
    title: 'Porsche 911 Carrera 4s Cabrio',
    bodywork: '',
    image: Porsche911Carrera4sCabrio2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 16,
    title: 'Porsche 911 GT2 RS',
    bodywork: '',
    image: Porsche911GT2RS2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 16,
    title: 'Porsche 911 GT3',
    bodywork: '',
    image: Porsche911GT32018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 16,
    title: 'Porsche 911 GT3 RS',
    bodywork: 'Coupé',
    image: Porsche911GT3RS,
    topSpeed: '312',
    acceleration: '3.2',
    passengers: '2',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 17,
    title: 'Porsche 911 Turbo',
    bodywork: '',
    image:  Porsche911Turbo1990,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 18,
    title: 'Porsche 935',
    bodywork: '',
    image: Porsche9352019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 19,
    title: 'Porsche Cayanne',
    bodywork: '',
    image:  PorscheCayanne2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 19,
    title: 'Porsche Cayanne Turbo',
    bodywork: '',
    image:  PorscheCayanneTurbo2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 20,
    title: 'Porsche Cayman 718 GTS',
    bodywork: '',
    image:  PorscheCayman718GTS2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 20,
    title: 'Porsche Panamera GTS',
    bodywork: '',
    image:  PorschePanameraGTS2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 20,
    title: 'Porsche Panamera GTS Sport Turismo',
    bodywork: '',
    image:  PorschePanameraGTSSportTurismo2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 20,
    title: 'Porsche Speedster',
    bodywork: '',
    image:  PorscheSpeedster2019,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 20,
    title: 'Porsche 550 Spyder',
    bodywork: '',
    image:  PorscheSpyder5501953,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 21,
    title: 'Porsche Taycan',
    bodywork: 'Berlina',
    image: PorscheTaycan2020,
    topSpeed: '260',
    acceleration: '3.4',
    passengers: '4',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 21,
    title: 'Porsche Taycan S',
    bodywork: 'Berlina',
    image: PorscheTaycanS2020,
    topSpeed: '260',
    acceleration: '3.4',
    passengers: '4',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 23,
    title: 'Range Rover Sport SVR',
    bodywork: '',
    image: RangeRoverSportSVR2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 23,
    title: 'Squir V2',
    bodywork: '',
    image: SquirV2,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 23,
    title: 'Subaru BRZ',
    bodywork: '',
    image: SubaruBRZ2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 23,
    title: 'Subaru Impresa WRX',
    bodywork: '',
    image: SubaruImpresaWRX2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 23,
    title: 'Subaru WRX STI',
    bodywork: '',
    image: SubaruWRXSTI2018,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 22,
    title: 'Tesla Model Y',
    bodywork: 'Sedán',
    image: TeslaModelY,
    topSpeed: '225',
    acceleration: '5.6',
    passengers: '5',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 23,
    title: 'Tesla Roadster',
    bodywork: '',
    image: TeslaRoadster,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
  {
    id: 24,
    title: 'Toyota Supra',
    bodywork: '',
    image: ToyotaSupra2020,
    topSpeed: '',
    acceleration: '',
    passengers: '',
    moreDetails: '',
    bookNow: '',
  },
]

export default CarsData